server:
  port: ${PORT:${SERVER_PORT:0}}

info:
  id: ${spring.application.name}:${server.port}

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

management:
  context-path: /admin

debug: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://kostromin-mb.local:8761}/eureka/
  instance:
    #hostname: ${INSTANCE_IP:localhost}
    #nonSecurePort: ${INSTANCE_PORT:${PORT:{SERVER_PORT:0}}}
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: ${management.context-path}/admin/info
    healthCheckUrlPath: ${management.context-path}/admin/health
  password: secret
