server:
  port: ${PORT:${SERVER_PORT:0}}

info:
  id: ${spring.application.name}:${server.port}

# management:
#   context-path: /admin
#   port: ${server.port}
# endpoints:
#   enabled: true
#   actuator:
#     enabled: true
#   restart:
#     enabled: true
#   shutdown:
#     enabled: true

debug: false

eureka:
  # server:
  #   waitTimeInMsWhenSyncEmpty: 0
  client:
  #   registerWithEureka: false
  #   fetchRegistry: false
  #   serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://kostromin-mb.local:8761}/eureka/
      registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
      homePageUrlPath: /${spring.application.name}
      statusPageUrlPath: /${spring.application.name}
  #   eurekaServerDNSName: kostromin-mb.local
  #   eurekaServerPort: 8761
  #   hostname: kostromin-mb.local
  #   nonSecurePort: ${local.server.port}
  #   leaseRenewalIntervalInSeconds: 10
  #   statusPageUrlPath: ${management.context-path}/info
  #   healthCheckUrlPath: ${management.context-path}/health
  #   virtualHostName: ${spring.application.name}
  #   appname: ${spring.application.name}
  # password: secret
    

logging:
  level:
    com.netflix.discovery: 'OFF'
