server:
  port: ${PORT:${SERVER_PORT:0}}

info:
  id: ${spring.application.name}:${server.port}

management:
  context-path: /admin
  port: ${server.port}
endpoints:
  enabled: true
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

debug: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://kostromin-mb.local:8761}/eureka/
  instance:
    eurekaServerDNSName: kostromin-mb.local
    eurekaServerPort: 8761
    hostname: kostromin-mb.local
    nonSecurePort: ${server.port}
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
    virtualHostName: ${spring.application.name}
    appname: ${spring.application.name}
  password: secret
